apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-mysql-app-pod
  namespace: {{ .Values.namespace }}  # Use the namespace defined in values.yaml
  labels:
    app: mysql-app
spec:
  containers:
  - name: mysql-app-container
    image: {{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}
    env:
      - name: DB_HOST
        value: "{{ .Values.mysql.dbHost }}"
      - name: DB_USER
        value: "{{ .Values.mysql.dbUser }}"
      - name: DB_PASSWORD
        value: "{{ .Values.mysql.dbPassword }}"
